// <auto-generated />
namespace SportsStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ProductUpdatedImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductUpdatedImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202004061941325_ProductUpdatedImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
